In [2]:
import torch
import numpy as np

In [3]:
random_array = np.random.randn(3,5)

In [4]:
random_array

array([[-0.99928948,  0.03665177, -0.74399256,  0.93249905, -0.63911143],
       [ 0.02832492,  1.18197497,  0.74408639,  0.58011184, -0.35311443],
       [ 0.38319578,  1.83856186, -1.96851434,  1.41846186,  0.60168668]])

In [6]:
type(random_array)

numpy.ndarray

In [7]:
random_array.shape

(3, 5)

In [9]:
random_array.ndim

2

In [10]:
random_matrix = torch.rand(size = (3,5))

In [11]:
random_matrix


tensor([[0.8390, 0.0421, 0.5898, 0.6782, 0.8123],
        [0.8746, 0.0232, 0.5532, 0.4498, 0.5186],
        [0.9771, 0.7288, 0.1601, 0.4071, 0.6356]])

In [12]:
random_matrix.ndim

2

In [13]:
random_matrix.shape

torch.Size([3, 5])

In [14]:
random_matrix.dtype

torch.float32

In [16]:
random_image_tensor = torch.rand(size=(224,224,3))

In [17]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [18]:
random_image_tensor.ndim

3

In [19]:
random_image_tensor

tensor([[[0.2905, 0.1471, 0.0574],
         [0.9221, 0.3078, 0.1109],
         [0.2871, 0.1884, 0.0954],
         ...,
         [0.1610, 0.8409, 0.3356],
         [0.0814, 0.2824, 0.4929],
         [0.1571, 0.9152, 0.9931]],

        [[0.0947, 0.0514, 0.2407],
         [0.6799, 0.9746, 0.7911],
         [0.1291, 0.7520, 0.8999],
         ...,
         [0.8635, 0.3577, 0.9981],
         [0.3523, 0.7365, 0.9607],
         [0.1693, 0.1797, 0.5682]],

        [[0.4115, 0.9410, 0.4019],
         [0.4941, 0.2213, 0.3361],
         [0.4252, 0.9544, 0.5467],
         ...,
         [0.4406, 0.7423, 0.1763],
         [0.1139, 0.3653, 0.1419],
         [0.8117, 0.5674, 0.5415]],

        ...,

        [[0.5284, 0.4325, 0.1707],
         [0.6527, 0.5588, 0.6930],
         [0.5084, 0.9269, 0.9256],
         ...,
         [0.8527, 0.8867, 0.4202],
         [0.6001, 0.2815, 0.9091],
         [0.8776, 0.3630, 0.3122]],

        [[0.6212, 0.0939, 0.1369],
         [0.5228, 0.3088, 0.0328],
         [0.

In [22]:
vector_with_arange = torch.arange(start=0, end=10, step=2)

In [23]:
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [24]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [26]:
similar_ones

tensor([1, 1, 1, 1, 1])

In [27]:
x_tensor = torch.tensor([1,2,3])

In [30]:
x_tensor = x_tensor + 15

In [31]:
x_tensor

tensor([16, 17, 18])

In [32]:
x_tensor.multiply(10)

tensor([160, 170, 180])

In [34]:
x_tensor.divide(10)

tensor([1.6000, 1.7000, 1.8000])