In [1]:
import torch
import numpy as np

In [2]:
matrix = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [5]:
# @ = matrix multiplication
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [6]:
torch.matmul(matrix,matrix)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [19]:
tensor1 = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

In [20]:
tensor2 = torch.tensor([[7,8],
                      [9,10],
                      [11,12]])

In [21]:
 tensor1 @ tensor2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [22]:
tensor2.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [23]:
tensor1 @ tensor2.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])