In [1]:
import torch

In [2]:
tensor = torch.arange(0,50,5)

In [3]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
tensor.sum()

tensor(225)

In [5]:
tensor.min()

tensor(0)

In [6]:
tensor.max()

tensor(45)

In [7]:
tensor.median()

tensor(20)

In [8]:
tensor = tensor.type(torch.float)

In [9]:
tensor

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [10]:
tensor.mean()

tensor(22.5000)

In [11]:
# argmax, argmin -> the index of min or max value

In [12]:
tensor.argmax()

tensor(9)

In [13]:
tensor.argmin()

tensor(0)

In [14]:
# manipulating tensor: reshaping, stacking, squeezing, unsqueezing

In [15]:
x = torch.arange(1,10,1)

In [16]:
x.shape

torch.Size([9])

In [17]:
x.ndim

1

In [18]:
x_reshaped = x.reshape(1,9)

In [19]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [20]:
x_reshaped.shape

torch.Size([1, 9])

In [21]:
x_reshaped.ndim

2

In [22]:
y = torch.randn(224,224,3)

In [23]:
y.shape

torch.Size([224, 224, 3])

In [24]:
x_reshaped = x.reshape(3,3)

In [25]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
# view

In [27]:
x_reshaped = x.reshape(9,1)

In [28]:
x_reshaped[0] = 20

In [29]:
x_reshaped 

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [30]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [31]:
x_view = x.view(9,1)

In [32]:
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [33]:
x_view[0] = 10

In [34]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [35]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [44]:
#  view = only contigous tensors

In [47]:
# stacking

In [54]:
x = torch.tensor([[1,2,3],
     [4,5,6]])

In [55]:
torch.stack([x,x,x,x], dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [57]:
torch.stack([x,x,x,x], dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [58]:
# squeeze & unsqueeze

In [59]:
x.shape

torch.Size([2, 3])

In [60]:
x.shape

torch.Size([2, 3])

In [61]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [65]:
x = torch.tensor([[1,2,3]])

In [67]:
x.shape

torch.Size([1, 3])

In [69]:
x.ndim

2

In [71]:
x.squeeze()

tensor([1, 2, 3])

In [73]:
x.unsqueeze(dim=0)

tensor([[[1, 2, 3]]])

In [74]:
# permute

In [76]:
x= torch.rand(size=(224,224,3))

In [77]:
x.shape

torch.Size([224, 224, 3])

In [78]:
x_permuted = x.permute(2,0,1)

In [80]:
x_permuted.shape

torch.Size([3, 224, 224])

In [81]:
# indexing & slicing

In [82]:
a = torch.arange(1,10,1)

In [83]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a = a.reshape(1,3,3)

In [89]:
a[0][0][0]

tensor(1)

In [90]:
a.shape

torch.Size([1, 3, 3])

In [91]:
a.ndim

3

In [92]:
a[:,0,0]

tensor([1])

In [93]:
a[:,1,0,]

tensor([4])

In [94]:
a[:,:,0]

tensor([[1, 4, 7]])

In [95]:
a[:,0,:]

tensor([[1, 2, 3]])

In [96]:
# random seed

In [98]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])